version: "2"

services:
  mongodb:
    image: "mongo"
    ports: 
      - '27017:27017'
  
  backend:
    build: ./backend/
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '5000:5000'
    depends_on: 
      - mongodb

  app:
    build: ./app/
    volumes: 
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    ports: 
      - '3000:3000'
    depends_on: 
      - backend